// <auto-generated />
//
// This file was automatically generated by cs-binding-generator
// https://github.com/cs-binding-generator/cs-binding-generator
// Generated on: 2026-01-02 16:59:35 UTC
// Command: /home/robindegen/Development/CsBindingGenerator/.venv/lib/python3.13/site-packages/pytest/__main__.py
// Do not modify this file directly
//

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Runtime.CompilerServices;

[assembly: System.Runtime.CompilerServices.DisableRuntimeMarshalling]
