// <auto-generated />
//
// This file was automatically generated by cs-binding-generator
// https://github.com/cs-binding-generator/cs-binding-generator
// Generated on: 2026-01-02 16:59:35 UTC
// Command: /home/robindegen/Development/CsBindingGenerator/.venv/lib/python3.13/site-packages/pytest/__main__.py
// Do not modify this file directly
//

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Runtime.CompilerServices;

namespace Bindings;

public enum MyEnum : uint
{
    VALUE1 = 0,
    VALUE2 = 1,
}


public static unsafe partial class NativeMethods
{
    [LibraryImport("test", EntryPoint = "test_function", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial void test_function(MyEnum* ptr);

    [LibraryImport("test", EntryPoint = "test_function2", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial void test_function2(MyEnum* out1, MyEnum* out2);

}