//
// This file was automatically generated by cs-binding-generator
// https://github.com/cs-binding-generator/cs-binding-generator
// Generated on: 2025-12-13 16:41:45 UTC
// Command: cs_binding_generator --config /home/robindegen/Development/CsBindingGenerator/test_dotnet/SDL3Test/cs-bindings.xml -o /home/robindegen/Development/CsBindingGenerator/test_dotnet/SDL3Test
// Do not modify this file directly
//

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Runtime.CompilerServices;

[assembly: System.Runtime.CompilerServices.DisableRuntimeMarshalling]

namespace Bindings;
